version: '3.4'

services:
  bitwarden:
    image: vaultwarden/server:1.33.2-alpine
    container_name: vaultwarden
    restart: always
    volumes:
      - ./data:/data  # 宿主机的当前目录下的 bw-data 目录 挂载到 容器内的 /data 目录
    env_file:
      - config.env
    ports:
      - "2000:80"
